### ISSUE TITLE
Errors in realise 1.0?

### ISSUE THREAD

**Issue by Minuta18** [maxtaran2010/ScaryWorld#1]
I download code (using github, because I am use linux). Then, I run it using `$ python3 main.py`. Code throws an error:
```[python] Traceback (most recent call last):
  File "/home/igors/Загрузки/ScaryWorld-main/main.py", line 164, in <module>
    app = App()
  File "/home/igors/Загрузки/ScaryWorld-main/main.py", line 38, in __init__
    self.font = pygame.font.Font('assets/font.ttf', 28)
FileNotFoundError: [Errno 2] No such file or directory: 'assets/font.ttf' 
```
How can I fix it?

**Comment by maxtaran2010** [comment]
I will upload new version and this problem should disappear.

**Comment by maxtaran2010** [comment]
Now should be working, we fixed bug.
